export const getAccountDetailsSQL = 
`
SELECT 
    G.LIEN_AMT, G.CLR_BAL_AMT, G.FORACID, G.ACCT_NAME, G.CIF_ID, G.SCHM_TYPE, G.SCHM_CODE, G.SOL_ID,
    G.ACCT_CRNCY_CODE, G.ACCT_OPN_DATE, G.ACCT_CLS_DATE, C.ACCT_STATUS AS CURRENT_ACCT_STATUS, S.ACCT_STATUS AS SAVINGS_ACCT_STATUS,
    E.BVN, D.BVN AS CORP_BVN, A.TIER,
    A.PREFERREDEMAIL, A.PHONE_CELL
FROM TBAADM.GAM G 
LEFT JOIN TBAADM.CAM C
    ON G.ACID = C.ACID
LEFT JOIN TBAADM.SMT S
    ON G.ACID = S.ACID
LEFT JOIN CUSTOM.BVN_LINK_MASTER E
    ON G.FORACID = E.FORACID
LEFT JOIN CUSTOM.CORP_BVN_SIGNATORIES D
    ON G.FORACID = D.ACCOUNT_NUMBER
LEFT JOIN CUSTOM.ATR_SCHM_TBL A
    ON G.SCHM_CODE = A.SCHM
    AND ROWNUM = 1
    AND A.DEL_FLG = 'N'
LEFT JOIN CRMUSER.ACCOUNTS A
    ON G.CIF_ID = A.ORGKEY
WHERE
  G.CIF_ID = (SELECT CIF_ID FROM TBAADM.GAM WHERE FORACID = :foracid )
`;

